# Etapa de build
FROM node:18-alpine AS builder

WORKDIR /app

# Instale dependências
COPY package.json package-lock.json ./
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

# Pule o linting no build de produção
RUN npm run build:skip-lint

# Etapa de execução
FROM node:18-alpine AS runner

WORKDIR /app

# Copie apenas os arquivos necessários da etapa de build
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

# Defina a variável de ambiente para a produção
ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

# Comando para rodar a aplicação Next.js
CMD ["npm", "start"]
