version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://admin:senha123@mongodb:27017
      - THE_ONE_API_KEY=SEU_TOKEN_DE_API
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
